const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");

const playwrightModule = process.env.PLAYWRIGHT_MODULE || "playwright";
const { chromium } = require(playwrightModule);

const command = process.argv[2];
const authDir = path.resolve(process.argv[3] || path.join(__dirname, "..", "user-data", "auth", "bilibili"));
const targetUrl = process.argv[4] || "https://www.bilibili.com/";
const ytDlpBin = process.env.YT_DLP_BIN || "yt-dlp";

const profileDir = path.join(authDir, "profile");
const cookiesPath = path.join(authDir, "cookies.txt");
const statusPath = path.join(authDir, "auth_status.json");

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeStatus(patch) {
  ensureDir(authDir);
  let previous = {};
  try {
    previous = JSON.parse(fs.readFileSync(statusPath, "utf8"));
  } catch {
    previous = {};
  }
  const next = {
    ...previous,
    ...patch,
    updatedAt: new Date().toISOString(),
    authDir,
    cookiesPath
  };
  fs.writeFileSync(statusPath, JSON.stringify(next, null, 2), "utf8");
  return next;
}

function readStatus() {
  try {
    return JSON.parse(fs.readFileSync(statusPath, "utf8"));
  } catch {
    return {};
  }
}

function normalizeUrl(url) {
  const value = String(url || "").trim();
  if (/^https?:\/\//i.test(value)) return value;
  return "https://www.bilibili.com/";
}

function isBilibiliLoginCookie(cookie) {
  return ["SESSDATA", "DedeUserID", "bili_jct"].includes(cookie.name);
}

function hasLoginCookies(cookies) {
  const names = new Set(cookies.map((cookie) => cookie.name));
  return names.has("SESSDATA") && (names.has("DedeUserID") || names.has("bili_jct"));
}

function toNetscapeCookieLine(cookie) {
  const domain = cookie.domain || ".bilibili.com";
  const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  const expires = Number.isFinite(cookie.expires) && cookie.expires > 0
    ? Math.floor(cookie.expires)
    : 0;
  return [
    domain,
    includeSubdomains,
    cookie.path || "/",
    secure,
    expires,
    cookie.name,
    String(cookie.value || "")
  ].join("\t");
}

function exportCookies(cookies) {
  ensureDir(authDir);
  const useful = cookies
    .filter((cookie) => /(^|\.)bilibili\.com$/i.test(cookie.domain || ""))
    .sort((a, b) => `${a.domain}${a.name}`.localeCompare(`${b.domain}${b.name}`));
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by ClipMind local Bilibili login helper.",
    ...useful.map(toNetscapeCookieLine)
  ];
  fs.writeFileSync(cookiesPath, `${lines.join("\n")}\n`, "utf8");
  return {
    cookiesPath,
    cookieCount: useful.length,
    loginCookieCount: useful.filter(isBilibiliLoginCookie).length,
    hasLoginCookies: hasLoginCookies(useful)
  };
}

function runCommand(bin, args, timeoutMs = 30000) {
  return new Promise((resolve) => {
    const child = spawn(bin, args, { windowsHide: true });
    let stdout = "";
    let stderr = "";
    const timeout = setTimeout(() => {
      try {
        child.kill();
      } catch {
        // Ignore.
      }
      resolve({ ok: false, code: null, stdout, stderr: `${stderr}\nTimed out after ${timeoutMs}ms`.trim() });
    }, timeoutMs);
    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString("utf8");
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString("utf8");
    });
    child.on("error", (error) => {
      clearTimeout(timeout);
      resolve({ ok: false, code: null, stdout, stderr: error.message || String(error) });
    });
    child.on("close", (code) => {
      clearTimeout(timeout);
      resolve({ ok: code === 0, code, stdout, stderr });
    });
  });
}

function trim(text, max = 700) {
  const value = String(text || "").replace(/\s+/g, " ").trim();
  return value.length > max ? `${value.slice(0, max)}...` : value;
}

async function openLogin() {
  ensureDir(profileDir);
  writeStatus({
    ok: false,
    phase: "opening",
    message: "Opening Bilibili login window.",
    targetUrl: normalizeUrl(targetUrl)
  });

  const context = await chromium.launchPersistentContext(profileDir, {
    channel: process.env.BROWSER_CHANNEL || "msedge",
    headless: false,
    viewport: { width: 1280, height: 880 },
    args: ["--disable-blink-features=AutomationControlled"]
  });
  const page = context.pages()[0] || await context.newPage();
  const loginUrl = "https://passport.bilibili.com/login";
  await page.goto(loginUrl, { waitUntil: "domcontentloaded", timeout: 60000 });
  writeStatus({
    ok: false,
    phase: "waiting_login",
    message: "Please finish Bilibili login in the opened browser window.",
    loginUrl,
    targetUrl: normalizeUrl(targetUrl)
  });

  const startedAt = Date.now();
  const timeoutMs = Number(process.env.BILIBILI_LOGIN_TIMEOUT_MS || 10 * 60 * 1000);
  while (Date.now() - startedAt < timeoutMs) {
    await page.waitForTimeout(2000);
    const cookies = await context.cookies(["https://www.bilibili.com", "https://passport.bilibili.com"]);
    const exported = exportCookies(cookies);
    if (exported.hasLoginCookies) {
      writeStatus({
        ok: true,
        phase: "logged_in",
        message: "Bilibili cookies are ready.",
        ...exported
      });
      await context.close();
      return { ok: true, ...exported };
    }
  }

  writeStatus({
    ok: false,
    phase: "timeout",
    message: "Login was not detected before timeout."
  });
  await context.close();
  return { ok: false, error: "Login timeout.", ...readStatus() };
}

async function verifyStatus() {
  const status = readStatus();
  const hasCookiesFile = fs.existsSync(cookiesPath);
  if (!hasCookiesFile) {
    return {
      ok: false,
      phase: status.phase || "missing",
      message: status.message || "No Bilibili cookies.txt has been generated.",
      authDir,
      cookiesPath,
      hasCookiesFile: false
    };
  }

  const cookieText = fs.readFileSync(cookiesPath, "utf8");
  const hasSessdata = /\bSESSDATA\b/.test(cookieText);
  const hasUser = /\bDedeUserID\b/.test(cookieText);
  const shouldVerify = process.env.BILIBILI_AUTH_SKIP_YTDLP_VERIFY !== "1";
  if (!shouldVerify) {
    return {
      ok: hasSessdata,
      phase: hasSessdata ? "cookie_file_ready" : "cookie_file_incomplete",
      message: hasSessdata ? "Bilibili cookie file exists." : "Cookie file exists but SESSDATA was not found.",
      authDir,
      cookiesPath,
      hasCookiesFile,
      hasSessdata,
      hasUser,
      verified: false
    };
  }

  const probeUrl = normalizeUrl(targetUrl);
  const result = await runCommand(ytDlpBin, [
    "--cookies",
    cookiesPath,
    "--dump-single-json",
    "--no-playlist",
    probeUrl
  ], Number(process.env.BILIBILI_AUTH_VERIFY_TIMEOUT_MS || 45000));
  const verified = result.ok;
  return {
    ok: hasSessdata && verified,
    phase: verified ? "verified" : "verify_failed",
    message: verified
      ? "Bilibili login cookies are verified."
      : "Cookie file exists, but yt-dlp could not verify the target link.",
    authDir,
    cookiesPath,
    hasCookiesFile,
    hasSessdata,
    hasUser,
    verified,
    targetUrl: probeUrl,
    ytDlp: {
      ok: result.ok,
      code: result.code,
      stderr: trim(result.stderr),
      stdout: trim(result.stdout)
    },
    lastStatus: status
  };
}

(async () => {
  if (command === "open") {
    const result = await openLogin();
    console.log(JSON.stringify(result, null, 2));
    return;
  }
  if (command === "status") {
    const result = await verifyStatus();
    console.log(JSON.stringify(result, null, 2));
    return;
  }
  console.error("Usage: node bilibili_auth_helper.cjs <open|status> <auth-dir> [target-url]");
  process.exit(2);
})().catch((error) => {
  writeStatus({
    ok: false,
    phase: "error",
    message: error.message || String(error)
  });
  console.error(error.stack || error.message || String(error));
  process.exit(1);
});
